Полная переработка навигаций внутри главного экрана (https://trello.com/c/ElwL7AeU)
korablique/recipe_calculator pull request #166
Opened 2019-08-06 21:31 UTC by blazern

Полная переработка навигаций внутри главного экрана (https://trello.com/c/ElwL7AeU)
+куча мелких правок

2019-08-10 20:15 UTC, korablique requested changes

2019-08-10 20:15 UTC, korablique commented on app/src/androidTest/java/korablique/recipecalculator/ui/mainscreen/MainScreenLoaderTest.java
> +        Intent expectedIntent = MainActivityController
в чём прикол?

2019-08-10 20:15 UTC, korablique commented on app/src/main/java/korablique/recipecalculator/ui/mainscreen/MainActivityController.java
> +            return;
почему? из чего это следует?

2019-08-10 20:15 UTC, korablique commented on app/src/main/java/korablique/recipecalculator/ui/mainscreen/MainActivityController.java
> +            fragmentsController.addFoodstuffsToHistory(selectedDate, foodstuffs);
а почему в другом месте есть метод, который называется openHistoryAndAddFoodstuffs, а здесь просто add, хотя на самом деле он откроет историю?

2019-08-10 20:15 UTC, korablique commented on app/src/main/java/korablique/recipecalculator/ui/mainscreen/MainActivityFragmentsController.java
> +        if (bottomNavigationView != null) {
как такое может быть?

2019-08-10 20:15 UTC, korablique commented on app/src/main/java/korablique/recipecalculator/ui/usergoal/UserParametersActivity.java
> +                        SplashScreenActivity.start(getBaseContext());
двойное моргание сплеш скрина - не круто, надо исправить

2019-08-11 17:28 UTC, blazern commented on app/src/androidTest/java/korablique/recipecalculator/ui/mainscreen/MainScreenLoaderTest.java
> +        Intent expectedIntent = MainActivityController
Legacy небольшой.
Убрал лишнюю переменную.

2019-08-11 17:28 UTC, blazern commented on app/src/main/java/korablique/recipecalculator/ui/mainscreen/MainActivityController.java
> +            return;
Добавил комментарий.

2019-08-11 17:28 UTC, blazern commented on app/src/main/java/korablique/recipecalculator/ui/mainscreen/MainActivityController.java
> +            fragmentsController.addFoodstuffsToHistory(selectedDate, foodstuffs);
Переименовал

2019-08-11 17:28 UTC, blazern commented on app/src/main/java/korablique/recipecalculator/ui/mainscreen/MainActivityFragmentsController.java
> +        if (bottomNavigationView != null) {
Никак. Убрал.

2019-08-11 17:28 UTC, blazern commented on app/src/main/java/korablique/recipecalculator/ui/usergoal/UserParametersActivity.java
> +                        SplashScreenActivity.start(getBaseContext());
Исправил.

2019-08-11 17:58 UTC, merged